packages:
  - playground
  - docs
  - packages/*
  - examples/*

catalog: null

catalogs:
  build:
    tsdown: ^0.15.6
  deps:
    automd: ^0.4.2
    bumpp: ^10.3.1
    jiti: ^2.6.1
    rimraf: ^6.0.1
    tinyglobby: ^0.2.15
    typescript: ^5.9.3
  lint:
    '@antfu/eslint-config': ^5.4.1
    eslint: ^9.37.0
    lint-staged: ^16.2.3
    simple-git-hooks: ^2.13.1
  test:
    '@vitest/coverage-v8': ^3.2.4
    vitest: ^3.2.4
  types:
    '@types/node': ^24.7.0

cleanupUnusedCatalogs: true
